// This file is auto-generated by Suprnova. Do not edit manually.
// Run `suprnova generate-types` to regenerate.

export interface AdminOverviewProps {
}

export interface DashboardProps {
  user: UserInfo;
}

export interface UserInfo {
  id: number;
  name: string;
  email: string;
}

export interface ForgotPasswordProps {
}

export interface HomeProps {
  title: string;
  message: string;
}

export interface LoginProps {
}

export interface RegisterProps {
}

export interface ResetPasswordProps {
  token: string;
}

export interface VerificationProps {
  email: string;
}

