// This file is auto-generated by Suprnova. Do not edit manually.
// Run `suprnova generate-types` to regenerate.

export type JsonValue = string | number | boolean | null | JsonValue[] | { [key: string]: JsonValue };

export interface AdminOverviewProps {
}

export interface BillingProps {
  mode: string;
  settings: JsonValue | null;
  configuration_error: string | null;
}

export interface DashboardProps {
  user: UserInfo;
}

export interface UserInfo {
  id: number;
  name: string;
  email: string;
}

export interface ForgotPasswordProps {
}

export interface HomeProps {
  title: string;
  message: string;
}

export interface LoginProps {
}

export interface RegisterProps {
}

export interface ResetPasswordProps {
  token: string;
}

export interface VerificationProps {
  email: string;
}
