<script setup lang="ts">
import { Head, Link } from '@inertiajs/vue3'
import type { OwnerListing, Paged } from '../../types/listings'
defineProps<{ listings: OwnerListing[]; pagination: Paged }>()
const readable = (text: string) => ({ none: 'None', free: 'Free plan', paid: 'Paid', test: 'Test payment', expired: 'Expired', disputed: 'Disputed', revoked: 'Revoked', draft: 'Draft', submitted: 'Awaiting review', approved: 'Approved', rejected: 'Rejected', archived: 'Archived', suspended: 'Suspended', published: 'Published', awaiting_review: 'Awaiting review', awaiting_payment: 'Awaiting payment', test_payment: 'Test payment only' })[text] ?? text.replace(/_/g, ' ')
const nextAction = (text: string) => ({ edit: 'Edit your listing.', submit: 'Submit your saved draft for review.', await_review: 'Wait for a moderator to review this revision.', checkout: 'Choose a publishing plan.', manage_payment: 'Manage your publishing payment.', none: 'No action is currently available.' })[text] ?? text.replace(/_/g, ' ')
</script>
<template>
  <Head title="Your listings" />
  <section class="directory-page"><header class="directory-heading directory-heading-actions"><div><h1>Your listings</h1><p>Manage content, review progress and publication.</p></div><Link href="/dashboard/listings/create" class="button button-primary">Create listing</Link></header>
    <div v-if="!listings.length" class="directory-empty"><h2>No listings yet</h2><p>Create a draft and submit it for review. After approval, choose a publishing plan.</p></div>
    <ul v-else class="directory-owner-list"><li v-for="listing in listings" :key="listing.id" class="directory-owner-row"><div><h2><Link :href="`/dashboard/listings/${listing.id}/edit`">{{ listing.current.title }}</Link></h2><p>{{ listing.current.summary }}</p></div><dl class="directory-statuses"><div><dt>Moderation</dt><dd>{{ readable(listing.moderation_status) }}</dd></div><div><dt>Payment</dt><dd>{{ readable(listing.payment_status) }}</dd></div><div><dt>Publication</dt><dd>{{ readable(listing.publication_status) }}</dd></div></dl><p v-if="listing.current.reason" class="notice"><strong>Review feedback:</strong> {{ listing.current.reason }}</p><p class="field-help">Next action: {{ nextAction(listing.next_action) }}</p><div class="directory-actions"><Link :href="`/dashboard/listings/${listing.id}/edit`" class="button button-secondary">{{ listing.archived ? 'View listing' : 'Edit listing' }}</Link><Link v-if="listing.next_action === 'checkout'" :href="`/dashboard/listings/${listing.id}/plans`" class="button button-primary">Choose publishing plan</Link><Link v-if="listing.publication_status === 'published'" :href="`/listings/${listing.slug}`" class="text-link">View public listing</Link></div></li></ul>
    <nav v-if="pagination.total > pagination.per_page" class="directory-pagination" aria-label="Your listing pages"><Link v-if="pagination.page > 1" :href="`/dashboard/listings?page=${pagination.page - 1}`" class="button button-secondary">Previous</Link><span>Page {{ pagination.page }}</span><Link v-if="pagination.page * pagination.per_page < pagination.total" :href="`/dashboard/listings?page=${pagination.page + 1}`" class="button button-secondary">Next</Link></nav>
  </section>
</template>
